POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbWVAbmFtZS5jb20iLCJpZCI6MSwiaWF0IjoxNjc4OTYyOTI0fQ.5nWBmZGf6BSmzm-FIXmIi9z2Zbzi5AwjsWONmNh8LCI

{
    "author": "Fake author",
    "url": "www.fake.com",
    "title": "Test title",
    "year": 1957
    
}